version: "3.9"

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:latest
    restart: always
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  traefik-ssl-certs:
    external: true

networks:
  traefik:
    external: true
